Lab1
BlackComrade/EPAMLabs_04_21 pull request #1
Opened 2021-04-23 10:30 UTC by BlackComrade

Me HW

2021-04-23 11:18 UTC, NikitaVarchenko requested changes
Нужно доделать замечания.

2021-04-23 11:18 UTC, NikitaVarchenko commented on Lab1/Lab1/BASCL/Program.cs
> +namespace BASCL
Что за название?

2021-04-23 11:18 UTC, NikitaVarchenko commented on Lab1/Lab1/BASCL/Program.cs
> +            float a, b;
Нужно чтобы код был самодокументируемый. названия осмысленные

2021-04-23 11:18 UTC, NikitaVarchenko commented on Lab1/Lab1/ConsoleApp1/Program.cs
> +    class Program
Зачем этот проект?

2021-04-25 10:58 UTC, BlackComrade commented on Lab1/Lab1/ConsoleApp1/Program.cs
> +    class Program
Он остался с форка

2021-05-04 11:47 UTC, NikitaVarchenko approved these changes
Принял

2021-05-04 11:55 UTC, merged